variable "compartment_ocid" {}
variable "tenancy_ocid" {}
variable "public_ip1" {}
variable "public_ip2" {}
variable "private_ip1" {}
variable "private_ip2" {}
variable "private_ip3" {}
variable "private_ip4" {}
variable "subnet_ad1" {}
variable "subnet_ad2" {}
variable "nsg_web_ocid" {}
variable "nsg_app_ocid" {}
